const charMap = {
  // LEFT_HAND_FINGER
  大指: { id: "lhf_da", svgFile: "../assets/svgs/lhf_da.svg", type: 'LEFT_HAND_FINGER' },
  食指: { id: "lhf_shi", svgFile: "../assets/svgs/lhf_shi.svg", type: 'LEFT_HAND_FINGER' },
  中指: { id: "lhf_zhong", svgFile: "../assets/svgs/lhf_zhong.svg", type: 'LEFT_HAND_FINGER' },
  名指: { id: "lhf_ming", svgFile: "../assets/svgs/lhf_ming.svg", type: 'LEFT_HAND_FINGER' },
  跪指: { id: "lhf_gui", svgFile: "../assets/svgs/lhf_gui.svg", type: 'LEFT_HAND_FINGER' },
  散: { id: "lhf_san", svgFile: "../assets/svgs/lhf_san.svg", type: 'LEFT_HAND_FINGER' },

  // RIGHT_HAND_FINGER
  擘: { id: "rhf_bo", svgFile: "../assets/svgs/rhf_bo.svg", type: 'RIGHT_HAND_FINGER' },
  托: { id: "rhf_tuo", svgFile: "../assets/svgs/rhf_tuo.svg", type: 'RIGHT_HAND_FINGER' },
  抹: { id: "rhf_mo", svgFile: "../assets/svgs/rhf_mo.svg", type: 'RIGHT_HAND_FINGER' },
  挑: { id: "rhf_tiao", svgFile: "../assets/svgs/rhf_tiao.svg", type: 'RIGHT_HAND_FINGER' },
  勾: { id: "rhf_gou", svgFile: "../assets/svgs/rhf_gou.svg", type: 'RIGHT_HAND_FINGER' },
  剔: { id: "rhf_ti", svgFile: "../assets/svgs/rhf_ti.svg", type: 'RIGHT_HAND_FINGER' },
  打: { id: "rhf_da", svgFile: "../assets/svgs/rhf_da.svg", type: 'RIGHT_HAND_FINGER' },
  摘: { id: "rhf_zhai", svgFile: "../assets/svgs/rhf_zhai.svg", type: 'RIGHT_HAND_FINGER' },
  历: { id: "rhf_li", svgFile: "../assets/svgs/rhf_li.svg", type: 'RIGHT_HAND_FINGER' },
  蠲: { id: "rhf_juan", svgFile: "./svgs/rhf_juan.svg", type: 'RIGHT_HAND_FINGER' },
  轮: { id: "rhf_lun", svgFile: "./svgs/rhf_lun.svg", type: 'RIGHT_HAND_FINGER' },
  琐: { id: "rhf_suo", svgFile: "./svgs/rhf_suo.svg", type: 'RIGHT_HAND_FINGER' },
  伏: { id: "rhf_fu", svgFile: "./svgs/rhf_fu.svg", type: 'RIGHT_HAND_FINGER' },
  滚: { id: "rhf_gun", svgFile: "./svgs/rhf_gun.svg", type: 'RIGHT_HAND_FINGER' },
  拂: { id: "rhf_fu2", svgFile: "./svgs/rhf_fu2.svg", type: 'RIGHT_HAND_FINGER' },
  至: { id: "rhf_zhi", svgFile: "./svgs/rhf_zhi.svg", type: 'RIGHT_HAND_FINGER' },
  拨: { id: "rhf_bo2", svgFile: "./svgs/rhf_bo2.svg", type: 'RIGHT_HAND_FINGER' },
  剌: { id: "rhf_la", svgFile: "./svgs/rhf_la.svg", type: 'RIGHT_HAND_FINGER' },
  掩: { id: "rhf_yan", svgFile: "./svgs/rhf_yan.svg", type: 'RIGHT_HAND_FINGER' },
  如一声: { id: "rhf_ruyisheng", svgFile: "./svgs/rhf_ruyisheng.svg", type: 'RIGHT_HAND_FINGER' },
  抹挑: { id: "rhf_motiao", svgFile: "./svgs/rhf_motiao.svg", type: 'RIGHT_HAND_FINGER' },
  勾剔: { id: "rhf_gouti", svgFile: "./svgs/rhf_gouti.svg", type: 'RIGHT_HAND_FINGER' },
  打摘: { id: "rhf_dazhai", svgFile: "./svgs/rhf_dazhai.svg", type: 'RIGHT_HAND_FINGER' },
  托擘: { id: "rhf_tuobo", svgFile: "./svgs/rhf_tuobo.svg", type: 'RIGHT_HAND_FINGER' },
  半轮: { id: "rhf_banlun", svgFile: "./svgs/rhf_banlun.svg", type: 'RIGHT_HAND_FINGER' },
  长琐: { id: "rhf_changsuo", svgFile: "./svgs/rhf_changsuo.svg", type: 'RIGHT_HAND_FINGER' },
  如一: { id: "rhf_ruyi", svgFile: "./svgs/rhf_ruyi.svg", type: 'RIGHT_HAND_FINGER' },
  滚拂: { id: "rhf_gunfu", svgFile: "./svgs/rhf_gunfu.svg", type: 'RIGHT_HAND_FINGER' },
  全扶: { id: "rhf_quanfu", svgFile: "./svgs/rhf_quanfu.svg", type: 'RIGHT_HAND_FINGER' },
  剌伏: { id: "rhf_lafu", svgFile: "./svgs/rhf_lafu.svg", type: 'RIGHT_HAND_FINGER' },
  打圆: { id: "rhf_dayuan", svgFile: "./svgs/rhf_dayuan.svg", type: 'RIGHT_HAND_FINGER' },
  搯起: { id: "rhf_taoqi", svgFile: "./svgs/rhf_taoqi.svg", type: 'RIGHT_HAND_FINGER' },
  抓起: { id: "rhf_zhuqi", svgFile: "./svgs/rhf_zhuqi.svg", type: 'RIGHT_HAND_FINGER' },
  带起: { id: "rhf_daiqi", svgFile: "./svgs/rhf_daiqi.svg", type: 'RIGHT_HAND_FINGER' },
  虚掩: { id: "rhf_xuyan", svgFile: "./svgs/rhf_xuyan.svg", type: 'RIGHT_HAND_FINGER' },
  推出: { id: "rhf_tuichu", svgFile: "./svgs/rhf_tuichu.svg", type: 'RIGHT_HAND_FINGER' },
  不动: { id: "rhf_budong", svgFile: "./svgs/rhf_budong.svg", type: 'RIGHT_HAND_FINGER' },

  // HUI_NUMBER
  "一徽": { id: "hui_1", svgFile: "../assets/svgs/hui_1.svg", type: 'HUI_NUMBER' },
  "二徽": { id: "hui_2", svgFile: "../assets/svgs/hui_2.svg", type: 'HUI_NUMBER' },
  "三徽": { id: "hui_3", svgFile: "../assets/svgs/hui_3.svg", type: 'HUI_NUMBER' },
  "四徽": { id: "hui_4", svgFile: "../assets/svgs/hui_4.svg", type: 'HUI_NUMBER' },
  "五徽": { id: "hui_5", svgFile: "../assets/svgs/hui_5.svg", type: 'HUI_NUMBER' },
  "六徽": { id: "hui_6", svgFile: "../assets/svgs/hui_6.svg", type: 'HUI_NUMBER' },
  "七徽": { id: "hui_7", svgFile: "../assets/svgs/hui_7.svg", type: 'HUI_NUMBER' },
  "八徽": { id: "hui_8", svgFile: "../assets/svgs/hui_8.svg", type: 'HUI_NUMBER' },
  "九徽": { id: "hui_9", svgFile: "../assets/svgs/hui_9.svg", type: 'HUI_NUMBER' },
  "十徽": { id: "hui_10", svgFile: "../assets/svgs/hui_10.svg", type: 'HUI_NUMBER' },
  "十一徽": { id: "hui_11", svgFile: "../assets/svgs/hui_11.svg", type: 'HUI_NUMBER' },
  "十二徽": { id: "hui_12", svgFile: "../assets/svgs/hui_12.svg", type: 'HUI_NUMBER' },
  "十三徽": { id: "hui_13", svgFile: "./assets/svgs/hui_13.svg", type: 'HUI_NUMBER' },
  "徽外": { id: "hui_wai", svgFile: "../assets/svgs/hui_wai.svg", type: 'HUI_NUMBER' },

  // FEN_NUMBER
  "一分": { id: "fen_1", svgFile: "../assets/svgs/fen_1.svg", type: 'FEN_NUMBER' },
  "二分": { id: "fen_2", svgFile: "../assets/svgs/fen_2.svg", type: 'FEN_NUMBER' },
  "三分": { id: "fen_3", svgFile: "../assets/svgs/fen_3.svg", type: 'FEN_NUMBER' },
  "四分": { id: "fen_4", svgFile: "../assets/svgs/fen_4.svg", type: 'FEN_NUMBER' },
  "五分": { id: "fen_5", svgFile: "../assets/svgs/fen_5.svg", type: 'FEN_NUMBER' },
  "六分": { id: "fen_6", svgFile: "../assets/svgs/fen_6.svg", type: 'FEN_NUMBER' },
  "七分": { id: "fen_7", svgFile: "../assets/svgs/fen_7.svg", type: 'FEN_NUMBER' },
  "八分": { id: "fen_8", svgFile: "../assets/svgs/fen_8.svg", type: 'FEN_NUMBER' },
  "九分": { id: "fen_9", svgFile: "../assets/svgs/fen_9.svg", type: 'FEN_NUMBER' },

  // XIAN_NUMBER
  "一弦": { id: "xian_1", svgFile: "../assets/svgs/xian_1.svg", type: 'XIAN_NUMBER' },
  "二弦": { id: "xian_2", svgFile: "../assets/svgs/xian_2.svg", type: 'XIAN_NUMBER' },
  "三弦": { id: "xian_3", svgFile: "../assets/svgs/xian_3.svg", type: 'XIAN_NUMBER' },
  "四弦": { id: "xian_4", svgFile: "../assets/svgs/xian_4.svg", type: 'XIAN_NUMBER' },
  "五弦": { id: "xian_5", svgFile: "../assets/svgs/xian_5.svg", type: 'XIAN_NUMBER' },
  "六弦": { id: "xian_6", svgFile: "../assets/svgs/xian_6.svg", type: 'XIAN_NUMBER' },
  "七弦": { id: "xian_7", svgFile: "../assets/svgs/xian_7.svg", type: 'XIAN_NUMBER' },

  // MOVE_FINGER
  进复: { id: "mf_jinfu", svgFile: "./svgs/mf_jinfu.svg", type: 'MOVE_FINGER' },
  退复: { id: "mf_tuifu", svgFile: "./svgs/mf_tuifu.svg", type: 'MOVE_FINGER' },
  往来: { id: "mf_wanglai", svgFile: "./svgs/mf_wanglai.svg", type: 'MOVE_FINGER' },
  上: { id: "mf_shang", svgFile: "./svgs/mf_shang.svg", type: 'MOVE_FINGER' },
  下: { id: "mf_xia", svgFile: "./svgs/mf_xia.svg", type: 'MOVE_FINGER' },
  进: { id: "mf_jin", svgFile: "./svgs/mf_jin.svg", type: 'MOVE_FINGER' },
  退: { id: "mf_tui", svgFile: "./svgs/mf_tui.svg", type: 'MOVE_FINGER' },
  复: { id: "mf_fu", svgFile: "./svgs/mf_fu.svg", type: 'MOVE_FINGER' },
  撞: { id: "mf_zhuang", svgFile: "./svgs/mf_zhuang.svg", type: 'MOVE_FINGER' },
  逗: { id: "mf_dou", svgFile: "./svgs/mf_dou.svg", type: 'MOVE_FINGER' },
  唤: { id: "mf_huan", svgFile: "./svgs/mf_huan.svg", type: 'MOVE_FINGER' },
  吟: { id: "mf_yin", svgFile: "./svgs/mf_yin.svg", type: 'MOVE_FINGER' },
  猱: { id: "mf_nao", svgFile: "./svgs/mf_nao.svg", type: 'MOVE_FINGER' },

  // SPECIAL_FINGER
  注: { id: "sf_zhu", svgFile: "./svgs/sf_zhu.svg", type: 'SPECIAL_FINGER' },
  绰: { id: "sf_chuo", svgFile: "./svgs/sf_chuo.svg", type: 'SPECIAL_FINGER' },

  // BOTH_FINGER
  掐撮三声: { id: "bf_qiazuosansheng", svgFile: "./svgs/bf_qiazuosansheng.svg", type: 'BOTH_FINGER' },
  分开: { id: "bf_fenkai", svgFile: "./svgs/bf_fenkai.svg", type: 'BOTH_FINGER' },
  同声: { id: "bf_tongsheng", svgFile: "./svgs/bf_tongsheng.svg", type: 'BOTH_FINGER' },
  应合: { id: "bf_yinghe", svgFile: "./svgs/bf_yinghe.svg", type: 'BOTH_FINGER' },
  放合: { id: "bf_fanghe", svgFile: "./svgs/bf_fanghe.svg", type: 'BOTH_FINGER' },

  // COMPLEX_FINGER
  掐撮: { id: "cf_qiazuo", svgFile: "./svgs/cf_qiazuo.svg", type: 'COMPLEX_FINGER' },
  双弹: { id: "cf_shuangtan", svgFile: "./svgs/cf_shuangtan.svg", type: 'COMPLEX_FINGER' },
  拨剌: { id: "cf_bola", svgFile: "./svgs/cf_bola.svg", type: 'COMPLEX_FINGER' },
  齐撮: { id: "cf_qizuo", svgFile: "./svgs/cf_qizuo.svg", type: 'COMPLEX_FINGER' },
  撮: { id: "cf_zuo", svgFile: "./svgs/cf_zuo.svg", type: 'COMPLEX_FINGER' },

  // MODIFIER
  引: { id: "mod_yin", svgFile: "./svgs/mod_yin.svg", type: 'MODIFIER' },
  淌: { id: "mod_tang", svgFile: "./svgs/mod_tang.svg", type: 'MODIFIER' },
  急: { id: "mod_ji", svgFile: "./svgs/mod_ji.svg", type: 'MODIFIER' },
  缓: { id: "mod_huan", svgFile: "./svgs/mod_huan.svg", type: 'MODIFIER' },
  紧: { id: "mod_jin", svgFile: "./svgs/mod_jin.svg", type: 'MODIFIER' },
  慢: { id: "mod_man", svgFile: "./svgs/mod_man.svg", type: 'MODIFIER' },

  // MARKER
  从再作: { id: "mark_congzaizuo", svgFile: "./svgs/mark_congzaizuo.svg", type: 'MARKER' },
  从头再作: { id: "mark_congtouzaizuo", svgFile: "./svgs/mark_congtouzaizuo.svg", type: 'MARKER' },
  少息: { id: "mark_shaoxi", svgFile: "./svgs/mark_shaoxi.svg", type: 'MARKER' },
  大息: { id: "mark_daxi", svgFile: "./svgs/mark_daxi.svg", type: 'MARKER' },
  入拍: { id: "mark_rupai", svgFile: "./svgs/mark_rupai.svg", type: 'MARKER' },
  入慢: { id: "mark_ruman", svgFile: "./svgs/mark_ruman.svg", type: 'MARKER' },
  句号: { id: "mark_juhao", svgFile: "./svgs/mark_juhao.svg", type: 'MARKER' },
  再作: { id: "mark_zaizuo", svgFile: "./svgs/mark_zaizuo.svg", type: 'MARKER' },
  曲终: { id: "mark_quzhong", svgFile: "./svgs/mark_quzhong.svg", type: 'MARKER' },
  操终: { id: "mark_caozhong", svgFile: "./svgs/mark_caozhong.svg", type: 'MARKER' },
  泛起: { id: "mark_fanqi", svgFile: "./svgs/mark_fanqi.svg", type: 'MARKER' },
  泛止: { id: "mark_fanzhi", svgFile: "./svgs/mark_fanzhi.svg", type: 'MARKER' },
  间: { id: "mark_jian", svgFile: "./svgs/mark_jian.svg", type: 'MARKER' },
};

export default charMap;